downstream: resctrl: fix undefined reference to lockdep_is_cpus_held()
lockdep_is_cpus_held() will only be compiled by the kernel when
CONFIG_HOTPLUG_CPU is defined. Otherwise, kernel test robot would report
the following compile error:

ld: vmlinux.o: in function `resctrl_get_domain_from_cpu':
include/linux/resctrl.h:291: undefined reference to `lockdep_is_cpus_held'

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202401252038.VOiTn1TA-lkp@intel.com/
Signed-off-by: Zeng Heng <zengheng4@huawei.com>